### PR TITLE
added installation instructions

### PR DESCRIPTION
**Pull request by tbuffington7**
Hi Randy! My name is Tyler Buffington and I am a PhD student at UT Austin working in Dr. Ezekoye's research group. I use FDS and I really appreciate now having syntax highlighting in Sublime Text. Because I have not used Sublime Packages much before, I struggled a bit to install the package, so I added some installation instructions to help others in the same boat as I was. Once again, thank you so much for this package!

-Tyler

### CODE REVIEW

**Comment by sbenkorichi** [comment]
step 3 is a bit not clear though. 
This is how it's done on mine. 
image

**Comment by rmcdermo** [comment]
@tbuffington7 
Nice to meet you.  And thanks for the PR!
I agree with @sbenkorichi .  I think that step 3 is not quite right.  At least on my system, you do not have to restart anything (I assume you meant restart Sublime).

**Comment by sbenkorichi** [comment]
That would make it applicable only to the current opened .fds file. I would rather say something like this
Open an .fds input file with Sublime, navigate to View -> Syntax --> Open all with current extension as -> select FDS.

This will make any .fds extension opened with the FDS Syntax highlighter.

**Comment by tbuffington7** [comment]
@sbenkorichi I saw your most recent comment after I made my last push to my fork, but I believe I addressed it. 

-Tyler

**Comment by rmcdermo** [comment]
Awesome job guys!  Tyler, thanks for the contribution.

Here is another To-Do, if anyone is so inclined: set up a Python script to checkout the FDS repo, scan the read.f90 source file, and update the Sublime syntax file if anything has changed.

**Comment by sbenkorichi** [comment]
Whether you believe it or not, this is what I wanted to do form long time ago.
Each time the .read changes there are some namelists aren't updated (as it's hard to keep updating each namelist.). 
I will try to sort this soon, unless Tyler is eager to work on it, which is fine for me.

**Comment by tbuffington7** [comment]
Salah, that sounds good. I have a lot on my plate right now with research, but I'd love to help in other ways down the road.

**Comment by sbenkorichi** [comment]
That's alright, 
Just contact Randy and let him know what you're working on/interested about, and I'm sure he would be of help.

**Comment by rmcdermo** [comment]
Not urgent.  Just on the dream list.  If we all keep adding/subtracting as we come across things, it is usually enough, but not very systematic.

**Pull request merged**
